import '../models/user.dart';
import '../models/organization.dart';
import '../models/vehicle.dart';
import '../models/vehicle_document.dart';
import '../models/journey.dart';
import '../models/fuel_and_service.dart';
import '../models/audit_and_notification.dart';

class SeedData {
  SeedData._();

  static final DateTime now = DateTime.now();

  static final List<Organization> demoOrganizations = [
    Organization(
      id: 'ORG-PWD-01',
      name: 'Public Works Department (PWD)',
      code: 'PWD-8042',
      adminId: 'USR-004',
      adminName: 'Vikram Singh',
      contactEmail: 'admin.pwd@up.gov.in',
      contactMobile: '+91 99000 11223',
      subscriptionTier: SubscriptionTier.enterprise,
      activeVehiclesCount: 4,
      activeMembersCount: 6,
      createdAt: DateTime(2026, 1, 15),
      isVerified: true,
    ),
    Organization(
      id: 'ORG-LOGIX-02',
      name: 'Logix Fleet Solutions Pvt Ltd',
      code: 'LOGIX-512',
      adminId: 'USR-006',
      adminName: 'Sameer Mehra',
      contactEmail: 'sameer@logixfleet.com',
      contactMobile: '+91 98123 00001',
      subscriptionTier: SubscriptionTier.pro,
      activeVehiclesCount: 3,
      activeMembersCount: 4,
      createdAt: DateTime(2026, 3, 10),
      isVerified: true,
    ),
  ];

  static final List<User> demoUsers = [
    User(
      id: 'USR-001',
      name: 'Dr. S. K. Verma',
      email: 'sk.verma@gov.in',
      mobile: '+91 98765 43210',
      employeeId: 'GOV-EE-4091',
      designation: 'Executive Engineer',
      department: 'Public Works Department',
      office: 'District Division 1, Noida',
      role: UserRole.user,
      assignedVehicleId: 'VEH-001',
      requiresApproval: true,
      approvingOfficerId: 'USR-003',
      approvingOfficerName: 'Anjali Sharma, IAS (SE)',
      createdAt: now.subtract(const Duration(days: 365)),
    ),
    User(
      id: 'USR-SUPER',
      name: 'Super Admin (You)',
      email: 'superadmin@vehiclelogbook.app',
      mobile: '+91 99999 00000',
      employeeId: 'SUPER-001',
      designation: 'Platform Administrator & Owner',
      organizationId: '',
      organizationName: 'Vehicle Log Book Platform',
      department: 'Platform Operations',
      office: 'Global Headquarters',
      role: UserRole.superAdmin,
      requiresApproval: false,
      createdAt: now.subtract(const Duration(days: 700)),
    ),
    User(
      id: 'USR-INDIV',
      name: 'Rahul Sharma',
      email: 'rahul.personal@gmail.com',
      mobile: '+91 98888 77777',
      employeeId: 'IND-01',
      designation: 'Independent Consultant',
      organizationId: '',
      organizationName: 'Self-Employed / Personal',
      department: 'Consulting',
      office: 'Home Office',
      role: UserRole.individualUser,
      isIndividual: true,
      requiresApproval: false,
      assignedVehicleId: 'VEH-001',
      createdAt: now.subtract(const Duration(days: 90)),
    ),
    User(
      id: 'USR-002',
      name: 'Rajesh Kumar',
      email: 'rajesh.driver@gov.in',
      mobile: '+91 98123 45678',
      employeeId: 'DRV-1024',
      designation: 'Senior Fleet Driver',
      department: 'Public Works Department',
      office: 'District Division 1, Noida',
      role: UserRole.driver,
      assignedVehicleId: 'VEH-001',
      requiresApproval: true,
      approvingOfficerId: 'USR-001',
      approvingOfficerName: 'Dr. S. K. Verma (EE)',
      createdAt: now.subtract(const Duration(days: 400)),
    ),
    User(
      id: 'USR-003',
      name: 'Anjali Sharma, IAS',
      email: 'anjali.sharma@gov.in',
      mobile: '+91 97111 22334',
      employeeId: 'IAS-2018-88',
      designation: 'Superintending Engineer & Approving Officer',
      department: 'Public Works Department',
      office: 'Regional Circle Office',
      role: UserRole.approvingOfficer,
      assignedVehicleId: 'VEH-002',
      requiresApproval: false,
      approvingOfficerId: null,
      approvingOfficerName: 'Self-Approver (HOD)',
      createdAt: now.subtract(const Duration(days: 500)),
    ),
    User(
      id: 'USR-004',
      name: 'Vikram Singh',
      email: 'vikram.admin@gov.in',
      mobile: '+91 99000 11223',
      employeeId: 'ADM-9001',
      designation: 'Department Fleet Administrator',
      department: 'Public Works Department',
      office: 'State Headquarters',
      role: UserRole.departmentAdmin,
      requiresApproval: false,
      approvingOfficerId: null,
      approvingOfficerName: 'Self-Approver (Admin)',
      createdAt: now.subtract(const Duration(days: 600)),
    ),
    User(
      id: 'USR-005',
      name: 'Arun Kumar',
      email: 'arun.kumar@gov.in',
      mobile: '+91 98111 22334',
      employeeId: '11000470',
      designation: 'Executive Engineer & Approving Officer',
      department: 'Public Works Department',
      office: 'Regional Circle Office',
      role: UserRole.approvingOfficer,
      assignedVehicleId: 'VEH-004',
      requiresApproval: false,
      approvingOfficerId: null,
      approvingOfficerName: 'Self-Approver (HOD)',
      createdAt: now.subtract(const Duration(days: 500)),
    ),
  ];

  static final List<Vehicle> demoVehicles = [
    Vehicle(
      id: 'VEH-001',
      registrationNumber: 'UP16 AB 1234',
      make: 'Toyota',
      model: 'Innova Crysta',
      vehicleType: 'SUV',
      fuelType: 'Diesel',
      manufacturingYear: 2023,
      currentOdometer: 52485.0,
      assignedOffice: 'District Division 1, Noida',
      assignedDriverId: 'USR-002',
      assignedDriverName: 'Rajesh Kumar',
      status: VehicleStatus.active,
      monthlyTargetKm: 3000.0,
      nextServiceKm: 55000.0,
      nextServiceDate: now.add(const Duration(days: 40)),
      fuelEfficiencyAvg: 13.8,
      documents: [
        VehicleDocument(
          id: 'DOC-001',
          vehicleId: 'VEH-001',
          type: DocumentType.rc,
          documentNumber: 'RC-UP16-2023-88912',
          issueDate: now.subtract(const Duration(days: 400)),
          expiryDate: now.add(const Duration(days: 1000)),
        ),
        VehicleDocument(
          id: 'DOC-002',
          vehicleId: 'VEH-001',
          type: DocumentType.insurance,
          documentNumber: 'NIC-POL-9921448',
          issueDate: now.subtract(const Duration(days: 300)),
          expiryDate: now.add(const Duration(days: 65)),
        ),
        VehicleDocument(
          id: 'DOC-003',
          vehicleId: 'VEH-001',
          type: DocumentType.puc,
          documentNumber: 'PUC-2026-90112',
          issueDate: now.subtract(const Duration(days: 160)),
          expiryDate: now.add(const Duration(days: 20)), // Expiring soon
        ),
        VehicleDocument(
          id: 'DOC-004',
          vehicleId: 'VEH-001',
          type: DocumentType.fitness,
          documentNumber: 'FIT-UP16-88219',
          issueDate: now.subtract(const Duration(days: 350)),
          expiryDate: now.add(const Duration(days: 380)),
        ),
      ],
    ),
    Vehicle(
      id: 'VEH-002',
      registrationNumber: 'DL01 CA 9988',
      make: 'Tata',
      model: 'Nexon EV Max',
      vehicleType: 'EV SUV',
      fuelType: 'Electric',
      manufacturingYear: 2024,
      currentOdometer: 18420.0,
      assignedOffice: 'Regional Circle Office',
      assignedDriverId: 'USR-002',
      assignedDriverName: 'Suresh Chauhan',
      status: VehicleStatus.active,
      monthlyTargetKm: 2000.0,
      nextServiceKm: 20000.0,
      nextServiceDate: now.add(const Duration(days: 25)),
      fuelEfficiencyAvg: 7.2, // km/kWh
      documents: [
        VehicleDocument(
          id: 'DOC-005',
          vehicleId: 'VEH-002',
          type: DocumentType.rc,
          documentNumber: 'RC-DL01-2024-11429',
          issueDate: now.subtract(const Duration(days: 200)),
          expiryDate: now.add(const Duration(days: 1200)),
        ),
        VehicleDocument(
          id: 'DOC-006',
          vehicleId: 'VEH-002',
          type: DocumentType.insurance,
          documentNumber: 'OIC-EV-88231',
          issueDate: now.subtract(const Duration(days: 350)),
          expiryDate: now.add(const Duration(days: 15)), // Expiring soon
        ),
        VehicleDocument(
          id: 'DOC-007',
          vehicleId: 'VEH-002',
          type: DocumentType.puc,
          documentNumber: 'PUC-EV-EXEMPT',
          issueDate: now.subtract(const Duration(days: 200)),
          expiryDate: now.add(const Duration(days: 500)),
        ),
      ],
    ),
    Vehicle(
      id: 'VEH-003',
      registrationNumber: 'UP32 BF 5566',
      make: 'Mahindra',
      model: 'Scorpio-N 4x4',
      vehicleType: 'Field SUV',
      fuelType: 'Diesel',
      manufacturingYear: 2023,
      currentOdometer: 64120.0,
      assignedOffice: 'Field Inspection Unit',
      assignedDriverId: 'USR-002',
      assignedDriverName: 'Mahesh Rawat',
      status: VehicleStatus.active,
      monthlyTargetKm: 3500.0,
      nextServiceKm: 65000.0,
      nextServiceDate: now.add(const Duration(days: 12)),
      fuelEfficiencyAvg: 11.5,
      documents: [
        VehicleDocument(
          id: 'DOC-008',
          vehicleId: 'VEH-003',
          type: DocumentType.puc,
          documentNumber: 'PUC-UP32-EXPIRED',
          issueDate: now.subtract(const Duration(days: 200)),
          expiryDate: now.subtract(const Duration(days: 2)), // EXPIRED
        ),
      ],
    ),
    Vehicle(
      id: 'VEH-004',
      registrationNumber: 'UP16 BL 8910',
      make: 'Maruti Suzuki',
      model: 'Celerio',
      vehicleType: 'Field SUV',
      fuelType: 'Diesel',
      manufacturingYear: 2017,
      currentOdometer: 104120.0,
      assignedOffice: 'Field Inspection Unit',
      assignedDriverId: 'USR-004',
      assignedDriverName: 'Rajesh Kumar',
      status: VehicleStatus.active,
      monthlyTargetKm: 3500.0,
      nextServiceKm: 65000.0,
      nextServiceDate: now.add(const Duration(days: 12)),
      fuelEfficiencyAvg: 11.5,
      documents: [
        VehicleDocument(
          id: 'DOC-008',
          vehicleId: 'VEH-004',
          type: DocumentType.puc,
          documentNumber: 'PUC-UP16-EXPIRED',
          issueDate: now.subtract(const Duration(days: 200)),
          expiryDate: now.subtract(const Duration(days: 2)), // EXPIRED
        ),
      ],
    ),    
  ];

  static final List<Journey> demoJourneys = [
    // Today's journey 1 - Used by Subordinate Officer (A. K. Gupta, Assistant Engineer) on dedicated vehicle
    Journey(
      id: 'JRN-2026-0824-01',
      localId: 'LOC-JRN-01',
      clientOperationId: 'OP-UUID-001',
      vehicleId: 'VEH-001',
      vehicleRegistration: 'UP16 AB 1234',
      vehicleModel: 'Toyota Innova Crysta',
      driverId: 'USR-002',
      driverName: 'Rajesh Kumar',
      officerId: 'USR-001',
      officerName: 'Dr. S. K. Verma (EE)',
      userOfficerName: 'Er. A. K. Gupta',
      userOfficerDesignation: 'Assistant Engineer (Subordinate)',
      isSubordinateJourney: true,
      officerSignatureText: 'A. K. Gupta (AE)',
      requiresApproval: true,
      department: 'Public Works Department',
      office: 'District Division 1, Noida',
      journeyDate: DateTime(now.year, now.month, now.day),
      startTime: DateTime(now.year, now.month, now.day, 9, 30),
      endTime: DateTime(now.year, now.month, now.day, 11, 45),
      startLocation: 'PWD Division Office, Sector 27',
      destination: 'Expressway Construction Site Sector 150',
      purpose: 'Highway & Drainage Site Inspection (Subordinate Duty)',
      openingOdometer: 52340.0,
      closingOdometer: 52415.0,
      officialDistance: 75.0,
      gpsDistance: 74.2,
      startLatitude: 28.5726,
      startLongitude: 77.3243,
      endLatitude: 28.4412,
      endLongitude: 77.4988,
      routePoints: [
        JourneyLocationPoint(
            latitude: 28.5726,
            longitude: 77.3243,
            timestamp: DateTime(now.year, now.month, now.day, 9, 30)),
        JourneyLocationPoint(
            latitude: 28.5110,
            longitude: 77.3820,
            timestamp: DateTime(now.year, now.month, now.day, 10, 15)),
        JourneyLocationPoint(
            latitude: 28.4412,
            longitude: 77.4988,
            timestamp: DateTime(now.year, now.month, now.day, 11, 45)),
      ],
      accompanyingOfficers: 'R. S. Negi (JE)',
      remarks: 'Dedicated vehicle utilized by AE for urgent culvert inspection.',
      status: JourneyStatus.pendingApproval,
      syncStatus: SyncStatus.synced,
      createdAt: DateTime(now.year, now.month, now.day, 9, 30),
      updatedAt: DateTime(now.year, now.month, now.day, 11, 45),
    ),
    // Today's journey 2 - Used by Dedicated Controlling Officer (Dr. S. K. Verma)
    Journey(
      id: 'JRN-2026-0824-02',
      localId: 'LOC-JRN-02',
      clientOperationId: 'OP-UUID-002',
      vehicleId: 'VEH-001',
      vehicleRegistration: 'UP16 AB 1234',
      vehicleModel: 'Toyota Innova Crysta',
      driverId: 'USR-002',
      driverName: 'Rajesh Kumar',
      officerId: 'USR-001',
      officerName: 'Dr. S. K. Verma',
      userOfficerName: 'Dr. S. K. Verma',
      userOfficerDesignation: 'Executive Engineer (Dedicated Officer)',
      isSubordinateJourney: false,
      officerSignatureText: 'Dr. S. K. Verma (EE)',
      requiresApproval: true,
      department: 'Public Works Department',
      office: 'District Division 1, Noida',
      journeyDate: DateTime(now.year, now.month, now.day),
      startTime: DateTime(now.year, now.month, now.day, 13, 15),
      endTime: DateTime(now.year, now.month, now.day, 15, 30),
      startLocation: 'Sector 150 Site',
      destination: 'Collectorate HQ & District Magistrate Office',
      purpose: 'District Infrastructure Review Meeting',
      openingOdometer: 52415.0,
      closingOdometer: 52485.0,
      officialDistance: 70.0,
      gpsDistance: 68.9,
      startLatitude: 28.4412,
      startLongitude: 77.4988,
      endLatitude: 28.5355,
      endLongitude: 77.3910,
      accompanyingOfficers: 'Dr. S. K. Verma (EE)',
      remarks: 'Attended DM coordination meeting.',
      status: JourneyStatus.approved,
      syncStatus: SyncStatus.synced,
      approvedBy: 'Anjali Sharma, IAS',
      approvedAt: DateTime(now.year, now.month, now.day, 16, 0),
      createdAt: DateTime(now.year, now.month, now.day, 13, 15),
      updatedAt: DateTime(now.year, now.month, now.day, 16, 0),
    ),
    // Yesterday's Journey - Dedicated Officer - Approved
    Journey(
      id: 'JRN-2026-0823-01',
      localId: 'LOC-JRN-03',
      clientOperationId: 'OP-UUID-003',
      vehicleId: 'VEH-001',
      vehicleRegistration: 'UP16 AB 1234',
      vehicleModel: 'Toyota Innova Crysta',
      driverId: 'USR-002',
      driverName: 'Rajesh Kumar',
      officerId: 'USR-001',
      officerName: 'Dr. S. K. Verma',
      userOfficerName: 'Dr. S. K. Verma',
      userOfficerDesignation: 'Executive Engineer',
      isSubordinateJourney: false,
      officerSignatureText: 'Dr. S. K. Verma (EE)',
      requiresApproval: true,
      department: 'Public Works Department',
      office: 'District Division 1, Noida',
      journeyDate: now.subtract(const Duration(days: 1)),
      startTime: now.subtract(const Duration(days: 1, hours: 8)),
      endTime: now.subtract(const Duration(days: 1, hours: 3)),
      startLocation: 'Division Office',
      destination: 'State PWD Lab, Lucknow HQ',
      purpose: 'Material Quality Testing Submission',
      openingOdometer: 52120.0,
      closingOdometer: 52340.0,
      officialDistance: 220.0,
      gpsDistance: 218.4,
      status: JourneyStatus.approved,
      syncStatus: SyncStatus.synced,
      approvedBy: 'Anjali Sharma, IAS',
      approvedAt: now.subtract(const Duration(days: 1, hours: 1)),
      createdAt: now.subtract(const Duration(days: 1, hours: 8)),
      updatedAt: now.subtract(const Duration(days: 1, hours: 1)),
    ),
    // Past Journey - Used by Subordinate Junior Engineer - Locked
    Journey(
      id: 'JRN-2026-0810-01',
      localId: 'LOC-JRN-04',
      clientOperationId: 'OP-UUID-004',
      vehicleId: 'VEH-001',
      vehicleRegistration: 'UP16 AB 1234',
      vehicleModel: 'Toyota Innova Crysta',
      driverId: 'USR-002',
      driverName: 'Rajesh Kumar',
      officerId: 'USR-001',
      officerName: 'Dr. S. K. Verma',
      userOfficerName: 'Er. R. S. Negi',
      userOfficerDesignation: 'Junior Engineer (Subordinate)',
      isSubordinateJourney: true,
      officerSignatureText: 'R. S. Negi (JE)',
      requiresApproval: true,
      department: 'Public Works Department',
      office: 'District Division 1, Noida',
      journeyDate: now.subtract(const Duration(days: 14)),
      startTime: now.subtract(const Duration(days: 14, hours: 9)),
      endTime: now.subtract(const Duration(days: 14, hours: 4)),
      startLocation: 'Division Office',
      destination: 'Yamuna River Bridge Site',
      purpose: 'Structural Health Inspection',
      openingOdometer: 51880.0,
      closingOdometer: 52120.0,
      officialDistance: 240.0,
      gpsDistance: 239.0,
      status: JourneyStatus.locked,
      syncStatus: SyncStatus.synced,
      approvedBy: 'Anjali Sharma, IAS',
      approvedAt: now.subtract(const Duration(days: 13)),
      lockedBy: 'Vikram Singh',
      lockedAt: now.subtract(const Duration(days: 10)),
      createdAt: now.subtract(const Duration(days: 14, hours: 9)),
      updatedAt: now.subtract(const Duration(days: 10)),
    ),
    // Journeys for Arun Kumar (USR-005) on VEH-004
    Journey(
      id: 'JRN-2026-0825-05',
      localId: 'LOC-JRN-05',
      clientOperationId: 'OP-UUID-005',
      vehicleId: 'VEH-004',
      vehicleRegistration: 'UP16 BL 8910',
      vehicleModel: 'Maruti Suzuki Celerio',
      driverId: 'USR-004',
      driverName: 'Rajesh Kumar',
      officerId: 'USR-005',
      officerName: 'Arun Kumar',
      userOfficerName: 'Arun Kumar',
      userOfficerDesignation: 'Executive Engineer',
      isSubordinateJourney: false,
      officerSignatureText: 'Arun Kumar (EE)',
      requiresApproval: false,
      department: 'Public Works Department',
      office: 'Regional Circle Office',
      journeyDate: DateTime(now.year, now.month, now.day),
      startTime: DateTime(now.year, now.month, now.day, 10, 0),
      endTime: DateTime(now.year, now.month, now.day, 13, 30),
      startLocation: 'Regional Circle Office, Noida',
      destination: 'Sector 62 Sub-Division Office',
      purpose: 'Field Inspection & Progress Review',
      openingOdometer: 104085.0,
      closingOdometer: 104120.0,
      officialDistance: 35.0,
      gpsDistance: 34.8,
      startLatitude: 28.5726,
      startLongitude: 77.3243,
      endLatitude: 28.6280,
      endLongitude: 77.3649,
      status: JourneyStatus.approved,
      syncStatus: SyncStatus.synced,
      approvedBy: 'Arun Kumar (Self-Approved)',
      approvedAt: DateTime(now.year, now.month, now.day, 13, 30),
      createdAt: DateTime(now.year, now.month, now.day, 10, 0),
      updatedAt: DateTime(now.year, now.month, now.day, 13, 30),
    ),
    Journey(
      id: 'JRN-2026-0824-06',
      localId: 'LOC-JRN-06',
      clientOperationId: 'OP-UUID-006',
      vehicleId: 'VEH-004',
      vehicleRegistration: 'UP16 BL 8910',
      vehicleModel: 'Maruti Suzuki Celerio',
      driverId: 'USR-004',
      driverName: 'Rajesh Kumar',
      officerId: 'USR-005',
      officerName: 'Arun Kumar',
      userOfficerName: 'Arun Kumar',
      userOfficerDesignation: 'Executive Engineer',
      isSubordinateJourney: false,
      officerSignatureText: 'Arun Kumar (EE)',
      requiresApproval: false,
      department: 'Public Works Department',
      office: 'Regional Circle Office',
      journeyDate: now.subtract(const Duration(days: 1)),
      startTime: now.subtract(const Duration(days: 1, hours: 8)),
      endTime: now.subtract(const Duration(days: 1, hours: 2)),
      startLocation: 'Regional Circle Office',
      destination: 'Greater Noida Expressway Site A',
      purpose: 'Drainage & Road Surface Inspection',
      openingOdometer: 104030.0,
      closingOdometer: 104085.0,
      officialDistance: 55.0,
      gpsDistance: 54.5,
      status: JourneyStatus.approved,
      syncStatus: SyncStatus.synced,
      approvedBy: 'Arun Kumar (Self-Approved)',
      approvedAt: now.subtract(const Duration(days: 1, hours: 2)),
      createdAt: now.subtract(const Duration(days: 1, hours: 8)),
      updatedAt: now.subtract(const Duration(days: 1, hours: 2)),
    ),
    // Anomaly Demonstration Journey - High GPS Discrepancy (>40%)
    Journey(
      id: 'JRN-2026-0824-07',
      localId: 'LOC-JRN-07',
      clientOperationId: 'OP-UUID-007',
      vehicleId: 'VEH-003',
      vehicleRegistration: 'UP32 BF 5566',
      vehicleModel: 'Mahindra Scorpio-N 4x4',
      driverId: 'USR-006',
      driverName: 'Sameer Mehra',
      officerId: 'USR-004',
      officerName: 'Vikram Singh',
      userOfficerName: 'Vikram Singh',
      userOfficerDesignation: 'Superintending Engineer',
      isSubordinateJourney: false,
      officerSignatureText: 'Vikram Singh (SE)',
      requiresApproval: true,
      department: 'Logix Fleet Solutions Pvt Ltd',
      office: 'Regional Transport Hub',
      journeyDate: now.subtract(const Duration(hours: 6)),
      startTime: now.subtract(const Duration(hours: 6)),
      endTime: now.subtract(const Duration(hours: 4)),
      startLocation: 'Central Depot Warehouse',
      destination: 'Outer Ring Bypass Checkpoint',
      purpose: 'Emergency Route Reconnaissance',
      openingOdometer: 31200.0,
      closingOdometer: 31285.0,
      officialDistance: 85.0,
      gpsDistance: 48.2, // ~43% variance with claimed odometer
      status: JourneyStatus.pendingApproval,
      syncStatus: SyncStatus.synced,
      createdAt: now.subtract(const Duration(hours: 6)),
      updatedAt: now.subtract(const Duration(hours: 4)),
    ),
  ];

  static final List<FuelEntry> demoFuelEntries = [
    FuelEntry(
      id: 'FUEL-001',
      vehicleId: 'VEH-001',
      date: now.subtract(const Duration(days: 3)),
      fuelStation: 'Indian Oil Auto Care, Sector 62',
      fuelType: 'Diesel',
      quantityLiters: 45.0,
      ratePerLiter: 89.62,
      totalAmount: 4032.90,
      odometerKm: 52100.0,
      receiptNumber: 'IOCL-994182',
      remarks: 'Official full tank refill',
    ),
    FuelEntry(
      id: 'FUEL-002',
      vehicleId: 'VEH-001',
      date: now.subtract(const Duration(days: 12)),
      fuelStation: 'BPCL Fuel Point, Greater Noida',
      fuelType: 'Diesel',
      quantityLiters: 50.0,
      ratePerLiter: 89.50,
      totalAmount: 4475.00,
      odometerKm: 51400.0,
      receiptNumber: 'BP-881290',
    ),
    FuelEntry(
      id: 'FUEL-003',
      vehicleId: 'VEH-004',
      date: now.subtract(const Duration(days: 2)),
      fuelStation: 'HPCL Station, Sector 18 Noida',
      fuelType: 'Petrol',
      quantityLiters: 30.0,
      ratePerLiter: 96.50,
      totalAmount: 2895.00,
      odometerKm: 104050.0,
      receiptNumber: 'HP-109283',
      remarks: 'Official tank refill for Celerio',
    ),
  ];

  static final List<MaintenanceRecord> demoMaintenanceRecords = [
    MaintenanceRecord(
      id: 'MAINT-001',
      vehicleId: 'VEH-001',
      serviceDate: now.subtract(const Duration(days: 45)),
      odometerKm: 50000.0,
      serviceType: '50,000 KM Periodic Maintenance',
      workPerformed: 'Engine oil replacement, oil filter, brake pad inspection, wheel alignment and rotation.',
      cost: 7850.00,
      vendor: 'Toyota Authorized Service Center, Noida',
      nextServiceKm: 55000.0,
      nextServiceDate: now.add(const Duration(days: 40)),
      invoiceNumber: 'INV-TOY-2026-9921',
    ),
    MaintenanceRecord(
      id: 'MAINT-002',
      vehicleId: 'VEH-004',
      serviceDate: now.subtract(const Duration(days: 60)),
      odometerKm: 100000.0,
      serviceType: '100,000 KM Major Overhaul & Service',
      workPerformed: 'Engine tune-up, coolant change, brake pad replacement, battery test.',
      cost: 6500.00,
      vendor: 'Maruti Suzuki Arena Workshop, Noida',
      nextServiceKm: 110000.0,
      nextServiceDate: now.add(const Duration(days: 90)),
      invoiceNumber: 'INV-MS-2026-3819',
    ),
  ];

  static final List<NotificationItem> demoNotifications = [
    NotificationItem(
      id: 'NOTIF-001',
      userId: 'USR-001',
      category: NotificationCategory.approval,
      title: 'Journey Approved',
      message: 'Your journey to Collectorate HQ (70 KM) has been approved by Anjali Sharma, IAS.',
      timestamp: now.subtract(const Duration(hours: 3)),
      isRead: false,
    ),
    NotificationItem(
      id: 'NOTIF-002',
      userId: 'USR-001',
      category: NotificationCategory.document,
      title: 'PUC Expiry Alert',
      message: 'Vehicle UP16 AB 1234 PUC expires in 20 days. Please arrange renewal.',
      timestamp: now.subtract(const Duration(days: 1)),
      isRead: false,
    ),
    NotificationItem(
      id: 'NOTIF-003',
      userId: 'USR-001',
      category: NotificationCategory.maintenance,
      title: 'Periodic Service Scheduled',
      message: 'Vehicle UP16 AB 1234 is approaching 55,000 KM service milestone.',
      timestamp: now.subtract(const Duration(days: 2)),
      isRead: true,
    ),
    NotificationItem(
      id: 'NOTIF-004',
      userId: 'USR-005',
      category: NotificationCategory.journey,
      title: 'Logbook Entry Certified',
      message: 'Your journey for UP16 BL 8910 (35.0 KM) was self-certified and saved.',
      timestamp: now.subtract(const Duration(hours: 2)),
      isRead: false,
    ),
  ];
}

